import Head from 'next/head'
import { useRouter } from 'next/router'

import styles from '../styles/Home.module.css'

const PageLayout = () => {
  const { route } = useRouter()
  const viewport = route.replace('/_viewport/', '')

  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel serverless user-agent-based rendering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vercel serverless user-agent-based rendering demo
        </h1>

        <p className={styles.description}>
          This page is currently view on {viewport} device.
        </p>
      </main>
    </div>
  )
}

export default PageLayout
